version: '3.8'
services:

  #Exchange Listener Service
  exchange-listener-1:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    hostname: exchange-listener-1
    container_name: exchange-listener-1
    restart: unless-stopped
    tty: true
    env_file:
      - .one.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start
  # exchange-listener-2:
  #   build:
  #     args:
  #       user: test
  #       uid: 1000
  #     context: ./
  #     dockerfile:  Dockerfile
  #   hostname: exchange-listener-2
  #   container_name: exchange-listener-2
  #   restart: unless-stopped
  #   tty: true
  #   env_file:
  #     - .two.env
  #   volumes:
  #     - app:/var/www/html
  #   command:
  #     - yarn
  #     - start-dev

#Docker Networks
networks:
  default:
    name: 'simple-trader'
    external: true

#Volumes
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./