version: '3.8'
services:

  #Exchange Listener Service
  exchange-listener-1:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    container_name: exchange-listener
    restart: unless-stopped
    tty: true
    depends_on:
      - influxdb
    env_file:
      - .one.env
    volumes:
      - app:/usr/src/app
    command:
      - yarn
      - start
  # exchange-listener-2:
  #   build:
  #     args:
  #       user: test
  #       uid: 1000
  #     context: ./
  #     dockerfile:  Dockerfile
  #   restart: unless-stopped
  #   tty: true
  #   env_file:
  #     - .two.env
  #   volumes:
  #     - app:/usr/src/app
  #   command:
  #     - yarn
  #     - start

  #InfluxDB Service
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    tty: true
    ports:
      - "8086:8086"
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: password
        DOCKER_INFLUXDB_INIT_ORG: simple-trader
        DOCKER_INFLUXDB_INIT_BUCKET: simple-trader
    volumes:
      - influxdbdata:/var/lib/influxdb2

#Docker Networks
networks:
  default:
    name: 'simple-trader'
    external: true

#Volumes
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
  influxdbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/influxdb