version: '3.5'
services:

  #Exchange Listener Service
  exchange-listener-1:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    hostname: exchange-listener-1
    container_name: exchange-listener-1
    restart: always
    env_file:
      - .one.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start

#Docker Networks
networks:
  default:
    name: 'simple-trader'
    external: true

#Volumes
volumes:
  app: